name: Copy Unraid Community Applications template(s) to templates repository

on:
  release:
    types: [ created ]
  workflow_dispatch: ~

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Establish variables
        id: vars
        run: |
          VERSION=${{ github.event.inputs.version || github.ref_name }}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=today::$(date +'%Y-%m-%d')

      - name: Open PR with template changes to unraid_templates
        uses: nwithan8/action-pull-request-another-repo@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.PR_OPEN_GITHUB_TOKEN }}
        with:
          # Will mirror folder structure (copying "templates" folder to "templates" folder in destination repo)
          source_folder: 'templates'
          destination_repo: 'nwithan8/unraid_templates'
          destination_base_branch: 'main'
          destination_head_branch: prerolls-${{ steps.vars.outputs.version }}
          user_email: 'nwithan8@users.noreply.github.com'
          user_name: 'nwithan8'
          pull_request_assignees: 'nwithan8'
